### ISSUE TITLE
Log integration

### ISSUE THREAD

**Issue by AllenFang** [SparkMonitor/varOne#33]
add log4j or slf4j on web backend for logging information or error.

**Comment by jackyoh** [comment]
Patch on these commits 
([5a9dd79](https://github.com/SparkMonitor/varOne/commit/5a9dd7995db8ffcaa68615aad6f046b32ba88931)), ([8a81b02](https://github.com/SparkMonitor/varOne/commit/8a81b02a79db1526ad94a220f2a09c9171c549e6)),([489f592](https://github.com/SparkMonitor/varOne/commit/489f5928e57106f0544ed5fc9e305263326a6242)),([b10cdd9](https://github.com/SparkMonitor/varOne/commit/b10cdd978fb65594bac88809007d823befd85873)),([b64468e](https://github.com/SparkMonitor/varOne/commit/b64468e3d789eabceef10acc1ee40824df5a3ce2)),([c7540bb](https://github.com/SparkMonitor/varOne/commit/c7540bb85f7534aaca69e322530ef3414be8f927)),([b469088](https://github.com/SparkMonitor/varOne/commit/b469088d77dd9fa1026ba6ad33d8a4a3c41f79d9)),([3d78996](https://github.com/SparkMonitor/varOne/commit/3d7899619a5039425a9fedf38cede633e0107ff0))

**Comment by AllenFang** [comment]
fix on v0.1.0-beta
